//
//  SearchInteractor.swift
//  IMusic
//
//  Created by Платон Конкилов on 08.04.2020.
//  Copyright (c) 2020 Платон Конкилов. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBusinessLogic {
    func doSomething(request: Search.Something.Request.RequestType)
}

protocol SearchDataStore {
  //var name: String { get set }
}

class SearchInteractor: SearchBusinessLogic, SearchDataStore {
    var networkService = NetworkService()
    var presenter: SearchPresentationLogic?
    var worker: SearchWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Search.Something.Request.RequestType) {
        
        switch request {
        case .some:
            print("interactor .some")
            presenter?.presentSomething(response: .some)
        case .getTrack(let searchTerm):
            print("interactor .getTrack")
            presenter?.presentSomething(response: Search.Something.Response.ResponseType.presentFooterView)
            networkService.fetchTask(searchText: searchTerm) {[weak self] (searchResponse) in
                
                self?.presenter?.presentSomething(response: Search.Something.Response.ResponseType.presentTracks(searchResponse: searchResponse))
            }
            
        }
    }
}
