//
//  SearchInteractor.swift
//  IMusic
//
//  Created by Платон Конкилов on 08.04.2020.
//  Copyright (c) 2020 Платон Конкилов. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBusinessLogic
{
  func doSomething(request: Search.Something.Request)
}

protocol SearchDataStore
{
  //var name: String { get set }
}

class SearchInteractor: SearchBusinessLogic, SearchDataStore
{
  var presenter: SearchPresentationLogic?
  var worker: SearchWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Search.Something.Request)
  {
    worker = SearchWorker()
    worker?.doSomeWork()
    
    let response = Search.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
