//
//  SearchModels.swift
//  IMusic
//
//  Created by Платон Конкилов on 08.04.2020.
//  Copyright (c) 2020 Платон Конкилов. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search {
  // MARK: Use cases
  
  enum Something {
    struct Request {
        enum RequestType {
            case some
            case getTrack(searchTerm: String)
        }
    }
    
    struct Response {
        enum ResponseType {
            case some
            case presentTracks(searchResponse: SearchResponse?)
            case presentFooterView 
        }
    }
    
    struct ViewModel {
        enum ViewModelData {
          case some
            case displayTracks (searchViewModel: SearchViewModel)
            case displayFooterView
        }
    }
  }
}

struct SearchViewModel {
    struct Cell: TrackCellViewModel {
        var iconUrlString: String?
        var trackName: String
        var collectionName: String
        var artistName: String
        var previewUrl: String?
    }
    
    let cells: [Cell]
}
